-- ============================================================
-- EduBridge AI — Initial Database Schema
-- Migration: 20260801065340_initial_schema
--
-- Creates the core tables for the anonymous, session-based
-- learning companion.
--
-- PRIVACY DESIGN NOTES:
--   • No auth.users relationship — sessions are fully anonymous.
--   • session_id is a client-generated UUID (v4).
--   • Raw audio is NEVER persisted — no audio table, no audio
--     column, no storage bucket.
--   • Persistence modes ('none', 'transcript', 'notes') are
--     enforced at the application/API layer, not by database
--     triggers.  The schema only provides the tables needed to
--     support the writes when the application decides to persist.
-- ============================================================


-- ============================================================
-- TABLE: sessions
-- ============================================================
-- Each row represents one anonymous classroom session.
-- session_id is generated by the CLIENT, not by the database.
-- There is NO relationship to auth.users.
-- ============================================================

CREATE TABLE sessions (
  session_id       uuid        PRIMARY KEY,
  created_at       timestamptz NOT NULL DEFAULT now(),
  persistence_mode text        NOT NULL DEFAULT 'none'
                     CHECK (persistence_mode IN ('none', 'transcript', 'notes')),
  language         text,
  consent_token    text
);

COMMENT ON TABLE  sessions IS 'Anonymous classroom sessions — session_id is client-generated.';
COMMENT ON COLUMN sessions.persistence_mode IS 'Controls what data the API layer may persist: none | transcript | notes.';
COMMENT ON COLUMN sessions.consent_token IS 'Optional client-provided consent token; nullable.';


-- ============================================================
-- TABLE: transcripts
-- ============================================================
-- Stores individual transcript chunks produced by speech-to-text.
-- Only written when persistence_mode IN (''transcript'', ''notes'').
-- ============================================================

CREATE TABLE transcripts (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      uuid        NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  chunk_index     int         NOT NULL,
  text            text        NOT NULL,
  translated_text text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE transcripts IS 'Speech-to-text transcript chunks, keyed to a session.';


-- ============================================================
-- TABLE: notes
-- ============================================================
-- One row per session containing AI-generated lecture notes.
-- Only written when persistence_mode = ''notes''.
-- Uses session_id as PK for a natural 1:1 relationship.
-- ============================================================

CREATE TABLE notes (
  session_id       uuid        PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
  content_markdown text        NOT NULL DEFAULT '',
  updated_at       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE notes IS 'AI-generated lecture notes — one row per session (1:1).';


-- ============================================================
-- TABLE: vocabulary
-- ============================================================
-- Technical terms detected during a session.
-- UNIQUE(session_id, term) prevents duplicate entries per session.
-- Only written when persistence_mode IN (''transcript'', ''notes'').
-- ============================================================

CREATE TABLE vocabulary (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  uuid        NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  term        text        NOT NULL,
  definition  text,
  analogy     text,
  translation text,
  created_at  timestamptz NOT NULL DEFAULT now(),

  UNIQUE (session_id, term)
);

COMMENT ON TABLE vocabulary IS 'Technical terms detected in a session — unique per (session, term).';


-- ============================================================
-- TABLE: chat_history
-- ============================================================
-- Stores Ask AI conversation messages.
-- Only written when persistence_mode = ''notes''.
-- ============================================================

CREATE TABLE chat_history (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  uuid        NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  role        text        NOT NULL CHECK (role IN ('user', 'assistant')),
  content     text        NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE chat_history IS 'Ask AI conversation messages, keyed to a session.';


-- ============================================================
-- INDEXES
-- ============================================================
-- Foreign-key columns that will be frequently queried or joined.
-- ============================================================

CREATE INDEX idx_transcripts_session  ON transcripts  (session_id, chunk_index);
CREATE INDEX idx_vocabulary_session   ON vocabulary   (session_id);
CREATE INDEX idx_chat_history_session ON chat_history  (session_id, created_at);


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
--
-- ⚠️  INTENTIONAL HACKATHON MVP TRADEOFF — PERMISSIVE RLS  ⚠️
--
-- EduBridge AI is anonymous and session-based.  There is:
--
--   • NO login system.
--   • NO Supabase Auth — auth.users is not used.
--   • NO auth.uid() available for policy conditions.
--
-- The application relies on UNGUESSABLE client-generated session
-- UUIDs (v4).  An attacker would need to guess a valid 128-bit
-- UUID to access another session's data.
--
-- The policies below use USING (true) / WITH CHECK (true) to
-- allow all operations.  RLS is still ENABLED so that the table
-- defaults to "deny" if policies are ever removed or replaced.
--
-- ┌──────────────────────────────────────────────────────────┐
-- │  🔒  PRODUCTION HARDENING REQUIRED                      │
-- │                                                          │
-- │  Before ANY production deployment these policies MUST    │
-- │  be replaced with policies that verify session ownership │
-- │  via signed anonymous session tokens validated at the    │
-- │  server / Edge Function layer.  For example:             │
-- │                                                          │
-- │    1. Issue a short-lived JWT containing session_id.     │
-- │    2. Validate the JWT in Edge Functions before writes.  │
-- │    3. Pass the verified session_id into RLS via          │
-- │       set_config('app.session_id', …, true) and check   │
-- │       current_setting('app.session_id') in policies.    │
-- └──────────────────────────────────────────────────────────┘
--


-- ── sessions ─────────────────────────────────────────────────

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sessions_select" ON sessions
  FOR SELECT
  USING (true);

CREATE POLICY "sessions_insert" ON sessions
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "sessions_update" ON sessions
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "sessions_delete" ON sessions
  FOR DELETE
  USING (true);


-- ── transcripts ──────────────────────────────────────────────

ALTER TABLE transcripts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "transcripts_select" ON transcripts
  FOR SELECT
  USING (true);

CREATE POLICY "transcripts_insert" ON transcripts
  FOR INSERT
  WITH CHECK (true);


-- ── notes ────────────────────────────────────────────────────

ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notes_select" ON notes
  FOR SELECT
  USING (true);

CREATE POLICY "notes_insert" ON notes
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "notes_update" ON notes
  FOR UPDATE
  USING (true)
  WITH CHECK (true);


-- ── vocabulary ───────────────────────────────────────────────

ALTER TABLE vocabulary ENABLE ROW LEVEL SECURITY;

CREATE POLICY "vocabulary_select" ON vocabulary
  FOR SELECT
  USING (true);

CREATE POLICY "vocabulary_insert" ON vocabulary
  FOR INSERT
  WITH CHECK (true);


-- ── chat_history ─────────────────────────────────────────────

ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "chat_history_select" ON chat_history
  FOR SELECT
  USING (true);

CREATE POLICY "chat_history_insert" ON chat_history
  FOR INSERT
  WITH CHECK (true);
